### ISSUE TITLE
add insertText for completion items

### ISSUE THREAD

**Issue by prabirshrestha** [rcjsuen/dockerfile-language-server-nodejs#135]
Currently my [asyncomplete-lsp.vim](https://github.com/prabirshrestha/asyncomplete-lsp.vim) plugin doesn't support `textEdits` for completions. Would it be possible to add `insertText` for the completion items?

According to the spec `CompletionItem` can contain an optional `insertText` which is used instead of label if it exists but ignored when `textEdit` is present. https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#completion-request

```typescript
/**
* A string that should be inserted a document when selecting
* this completion. When `falsy` the label is used.
*/
insertText?: string;

/**
 * An edit which is applied to a document when selecting this completion. When an edit is provided the value of
 * `insertText` is ignored.
 *
 * *Note:* The range of the edit must be a single line range and it must contain the position at which completion
 * has been requested.
 */
textEdit?: TextEdit;

```

**Comment by rcjsuen** [comment]
@prabirshrestha Wouldn't you fall back to the `label` property of `CompletionItem` in that case?

**Comment by prabirshrestha** [comment]
I do fallback to `label` but label currently contains too much details. This mean I need to delete `source dest`.

```json
{
  "label": "ADD source dest",
  "data": "ADD",
  "textEdit": {
    "range": {
      "end": {
        "character": 0,
        "line": 4
      },
      "start": {
        "character": 0,
        "line": 4
      }
    },
    "newText": "ADD"
  },
  "kind": 14,
  "insertTextFormat": 1
}
```

**Comment by rcjsuen** [comment]
Ah, I see. That's right. The label includes the instruction as well as its "standard" arguments.

I'm not sure how I feel about adding this information because the protocol makes it clear that `insertText` should be ignored if `textEdit` is provided. I guess the other language servers that you have tested thus far have opted to include values for both `insertText` and `textEdit`?

**Comment by prabirshrestha** [comment]
I'm working on implementing the LSP client https://github.com/prabirshrestha/vim-lsp and don't think will work on the `textEdit` feature any time soon. For the servers I have tried most of them don't seem to support `textEdit`.

This is how I'm understanding the spec:
The spec says `When an edit is provided the value of insertText is ignored.`. This means ideally the server could return both `insertText` and `textEdit` but if the client supports `textEdit` it should use that instead of `insertText`. Since my client (vim-lsp) doesn't support `textEdit` it would use `insertText` and vscode supports `insertText` so it would work for both editors.

I don't see any options in `ClientCapabilities` that can explicitly opt for `insertText` or `textEdit` in completion options. But it does seem to include `applyEdit` for `WorkspaceClientCapabilities` but don't think this is related.

**Comment by rcjsuen** [comment]
@prabirshrestha I think one reason the language servers you've tested so far haven't used `textEdit` is because there was no need for them to *replace* the text in the document.

While it is okay for Dockerfile instructions to be written in lowercase, convention states that they should be written in uppercase. Because of this convention, the language server is written so that completion items will convert lowercase instructions into uppercase.
```Dockerfile
FROM node
expo
```
For example, if the above Dockerfile was opened, invoking `textDocument/completion` will replace the `expo` with `EXPOSE` after the completion item has been applied to the document.

I guess you are calculating prefixes yourself? If you use the `label` property, you'd still have to remove the first four `EXPO` characters so that you only append `SE`, correct?

**Comment by prabirshrestha** [comment]
I temporarily hacked `asyncomplete-lsp.vim` to use `toupper()` and here is an example with rust lang server. Notice how I start with lowercase `pan` but once I press tab it gets converted to uppercase `PANIC_ABORT`. This means `insertText` doesn't need to be in small letter.

![uppercase](https://user-images.githubusercontent.com/287744/29006941-60438d94-7aae-11e7-86ad-799c8d70b984.gif)

When I send the `textDocument/completion` I send the notification when `e` is typed. Results are cached so typing `ex` wouldn't make any request and vim uses prefix to filter out. Since I told to ignore case it will show the result `EXPOSE` even when I typed `ex`. So when I select `EXPOSE` it will replace `ex` with `EXPOSE` since my start column was where the first `e` is and not after `x` ie. it won't be `exEXPOSE` or `exPOSE`.

**Comment by rcjsuen** [comment]
@prabirshrestha Based on your [earlier comment](https://github.com/rcjsuen/dockerfile-language-server-nodejs/issues/135#issuecomment-320487325), I'm assuming that you don't have `snippetSupport` enabled, correct?

**Comment by prabirshrestha** [comment]
I don't have snippet support. Also shouldn't the server look at `TextDocumentClientCapabilities` and `completion.completionItem.snippetSupport`? Currently `vim-lsp` send clientCapabilities as `{}`.

**Comment by prabirshrestha** [comment]
Based on this seems like I also need to send correct ClientCapabilities to the server.

>New: ClientCapabilities now define capabilities for dynamic registration, workspace and text document features the client supports. The experimental can be used to pass experimential capabilities under development. For future compatibility a ClientCapabilities object literal can have more properties set than currently defined. Servers receiving a ClientCapabilities object literal with unknown properties should ignore these properties. A missing property should be interpreted as an absence of the capability. If a property is missing that defines sub properties all sub properties should be interpreted as an absence of the capability.

**Comment by rcjsuen** [comment]
@prabirshrestha You are right. The server should check for that field and [it does do that](https://github.com/rcjsuen/dockerfile-language-server-nodejs/blob/6d38cdb266f16370f725bcc323bbf466d60d77da/src/server.ts#L46-L51).

Since you are not using snippets, the labels shouldn't include any arguments as it can confuse the user. For example, the user will see `ARG name=value` but only `ARG` gets appended into the document. I will change the `label` to only include `ARG` if `snippetSupport` is `false` and that should hopefully allow you to simply use `label` when applying the completion item. I have opeend #136 for this.

**Comment by prabirshrestha** [comment]
Sounds good. Feel free to close this issue as I have already subscribed to the other issue.

**Comment by rcjsuen** [comment]
`insertText` will not be included in completion items. Clients that don't have `snippetSupport` enabled can use the `label` property instead.
