### ISSUE TITLE
Add completion items for image tags

### ISSUE THREAD

**Issue by rcjsuen** [rcjsuen/dockerfile-language-server-nodejs#154]
```Dockerfile
FROM alpine:
```
Given the above Dockerfile, invoking code completion should provide a list of tags for the `alpine` image. We can use the [Docker Registry HTTP API V2](https://docs.docker.com/registry/spec/api/) to support this feature.

**Comment by rodhash** [comment]
Hello @rcjsuen  

Just to clarify something pls: does completion provide suggestions for both the image name and its tags, or is it expected to complete only the tags?

I know this issue focuses on tags but since I didn’t see one for image names, is completion supposed to provide images name too?


Thank you
