### ISSUE TITLE
Cannot find module 'vscode-languageserver-protocol/lib/protocol.sematicTokens.proposed'

### ISSUE THREAD

**Issue by raxod502** [rcjsuen/dockerfile-language-server-nodejs#247]
The server fails to start after being installed.

```
% npm i dockerfile-language-server-nodejs

added 10 packages, and audited 10 packages in 672ms

found 0 vulnerabilities
% npx docker-langserver
node:internal/modules/cjs/loader:928
  throw err;
  ^

Error: Cannot find module 'vscode-languageserver-protocol/lib/protocol.sematicTokens.proposed'
Require stack:
- /tmp/jpojoijiog/node_modules/dockerfile-language-service/lib/dockerSemanticTokens.js
- /tmp/jpojoijiog/node_modules/dockerfile-language-service/lib/languageService.js
- /tmp/jpojoijiog/node_modules/dockerfile-language-service/lib/main.js
- /tmp/jpojoijiog/node_modules/dockerfile-language-server-nodejs/lib/server.js
- /tmp/jpojoijiog/node_modules/dockerfile-language-server-nodejs/bin/docker-langserver
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at /tmp/jpojoijiog/node_modules/dockerfile-language-service/lib/dockerSemanticTokens.js:16:45
    at /tmp/jpojoijiog/node_modules/dockerfile-language-service/lib/dockerSemanticTokens.js:3:17
    at Object.<anonymous> (/tmp/jpojoijiog/node_modules/dockerfile-language-service/lib/dockerSemanticTokens.js:9:3)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/tmp/jpojoijiog/node_modules/dockerfile-language-service/lib/dockerSemanticTokens.js',
    '/tmp/jpojoijiog/node_modules/dockerfile-language-service/lib/languageService.js',
    '/tmp/jpojoijiog/node_modules/dockerfile-language-service/lib/main.js',
    '/tmp/jpojoijiog/node_modules/dockerfile-language-server-nodejs/lib/server.js',
    '/tmp/jpojoijiog/node_modules/dockerfile-language-server-nodejs/bin/docker-langserver'
  ]
}
npm ERR! code 1
npm ERR! path /tmp/jpojoijiog
npm ERR! command failed
npm ERR! command sh -c docker-langserver

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/raxod502/.npm/_logs/2020-12-18T02_06_38_786Z-debug.log
```

This appears to be with version 0.1.1 of the package, according to the generated `package.json`. Ubuntu 20.04.

**Comment by rcjsuen** [comment]
@raxod502 Thank you for your bug report. I can reproduce the issue.

**Comment by raxod502** [comment]
Nice! You have my utmost sympathy, by the way, for having to debug things related to `vscode-languageserver-protocol`. I've used that package before, and it was most assuredly not fun :cry:

**Comment by GopherJ** [comment]
any news about this?

**Comment by rcjsuen** [comment]
@GopherJ Sorry, I'm busy with my day job but hope to have some time over the holidays. Which editor is this affecting?

**Comment by christianbundy** [comment]
I'm building a [small editor that only speaks LSP](https://github.com/christianbundy/lsp-editor) and it's affecting me, since I can't start the language server.

**Comment by GopherJ** [comment]
@rcjsuen hi, I'd really want to test coc-docker and imporve it, it uses this project internally, could you guide us on how to fix it so that we can maybe help.

Merry Christmas BTW! Be safe guys

**Comment by rcjsuen** [comment]
> could you guide us on how to fix it so that we can maybe help.

@GopherJ I have a hunch about what the issue is and am actively looking at it.

> I see your change on docker-language-service but maybe it's not released and used here?

The language server is powered by three libraries and the language service is one of them. I'm cutting releases for the other dependent libraries as we speak so that I can merge them into the next release of the language server.

> Merry Christmas BTW! Be safe guys!

Thank you and I hope everyone is able to take some time off over the holidays.

**Comment by rcjsuen** [comment]
@raxod502 Thanks again for bringing this issue to my attention. From what I can find, it seems this was due to my use of proposed LSP 3.16 APIs without specifying hard version requirements in my `package.json` file. This led to issues when they were replaced by the official API on [December 14th](https://github.com/microsoft/vscode-languageserver-node/commit/24f04a63fb66fcb06de3c061a8a32c563e40da24). This explains why this was not reported earlier given that 0.1.1 has been out in the wild for about half a year.

The new 0.2.0 release that has just been published to npm should be fixed. If everyone on this ticket could take a look see and confirm that, you have my thanks!

Lastly, I want to thank everyone again for your patience. :)

**Comment by raxod502** [comment]
Wonderful, thank you so much! I can confirm the updated version of the language server is working.

**Comment by christianbundy** [comment]
Thank you! I can confirm that `textDocument`semanticTokens/full` works beautifully. :sparkles: 

![image](https://user-images.githubusercontent.com/537700/103183082-3bf8f400-4865-11eb-846b-b7beeef50189.png)
